### ISSUE TITLE
Why do we use signed int64 in the Context?

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/basictracer-go#20]
cc @bcronin @bensigelman 

I recently changed our in-house tracer to use `uint64` because it ran into compatibility issues with other traces, because it was serializing large IDs as negative hex strings.  I don't see a lot of benefits in keeping these fields signed.

**Comment by bensigelman** [comment]
yes, unsigned SGTM!

**Comment by bg451** [comment]
+1

cc @tschottdorf

**Comment by tschottdorf** [comment]
Sure.
