### ISSUE TITLE
add option to limit number of log events

### ISSUE THREAD

**Issue by RaduBerinde** [opentracing/basictracer-go#38]
We had an issue where we were doing endless retries and the memory inside basictracer grew indefinitely. It would be useful to add an option to limit the number of events in a span.

If adding this option is ok, I can work on the PR.

**Comment by yurishkuro** [comment]
Sounds like a good idea. Only please have sensible defaults so that it works for most people without having to configure the limits, e.g. up to 20 tags per span, up to 10 logs per span with up to 5 fields per log.

@bensigelman do you have better defaults?

cc @tschottdorf

**Comment by RaduBerinde** [comment]
In the interest of backward compatibility (especially when used as part of other tracers, e.g. lightstep), I would say that by default it should behave as it does now (i.e. no limits).

**Comment by jmacd** [comment]
I would prefer to have limits, by default, with in-band annotations
indicating that some data was dropped. E.g., a meta-tag saying
"tags.dropped:4" or a log message saying "did not record 25 log events",
etc.
ᐧ

**Comment by bensigelman** [comment]
Yeah, I think sensible/conservative defaults would be sensible and conservative. This is about protecting the application as much as the tracing system.

+1 to the feature. @RaduBerinde are you volunteering to do the work? :)

**Comment by RaduBerinde** [comment]
I am - for limiting log events at least. Limiting tags and other things can be done separately if it's an actual concern in practice.

**Comment by bensigelman** [comment]
@RaduBerinde great! Happy to review a PR.
